### ISSUE TITLE
Blocks CMD+CTRL+Q (display lock)

### ISSUE THREAD

**Issue by hsph** [dteoh/SlowQuitApps#64] opened 2019-12-16 08:57 UTC
Usually I lock my display by pressing ⌘ + ⌃ + Q. If I press this combination, whilst SlowQuitApps is running, it the ring activates and blocks the action. If I keep the keys pressed, after the delay, instead of locking my display, my current app quits.

**Comment by dteoh** [comment] 2020-01-02 05:57
I can't reproduce this issue in my setup. I have tried pressing first ⌘ then ^ then Q and also first ^ then ⌘ then Q. In both cases the display is locked immediately.

**Comment by hsph** [comment] 2020-01-02 09:30
That's odd... For me "the ring" is triggered regardless of which key I'm pressing first. If it helps, I installed it via Homebrew, (https://github.com/dteoh/SlowQuitApps/releases/download/v0.7.3/SlowQuitApps.zip) and I'm running Catalina on this machine:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/9482337/71660272-c68a3e80-2d4a-11ea-8a83-04a71fdd6c65.png">

**Comment by hsph** [comment] 2020-01-02 09:31
That's odd... For me "the ring" is triggered regardless of which key I'm pressing first. If it helps, I installed it via Homebrew, (https://github.com/dteoh/SlowQuitApps/releases/download/v0.7.3/SlowQuitApps.zip) and I'm running Catalina on this machine:
![image](https://user-images.githubusercontent.com/9482337/71660366-15d06f00-2d4b-11ea-8446-f2029eb62eba.png)

**Comment by dteoh** [comment] 2020-01-02 11:03
Ah I see, I'm still on Mojave. Going to attribute this to some internal change in Catalina. I will try adding an exclusion to the Ctrl key modifier.

**Comment by dteoh** [comment] 2020-01-03 02:32
Fixed in v0.8.0. Cmd + Ctrl key sequences will be ignored.

**Closed by dteoh** 2020-01-03 02:32 UTC

**Comment by hsph** [comment] 2020-01-03 08:46
Brillant, it works perfectly now. Thanks for your fast help, much appreciated!
